name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:          # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          curl --silent --show-error --fail https://www.makhmalifresh.com/health || exit 0